In [1]:

import numpy as np
import pandas as pd

import pickle

geometric_data = pickle.load(open("../data/nfl-big-data-bowl-2024/_play_by_play_geometric_features.pkl", "rb"))

In [22]:
#  get the tacklers
print("Keys:", list(geometric_data[0].keys()))
test_play = geometric_data[15]
onfield = test_play["players_on_the_field"]
tacklers = onfield.loc[(onfield["tackle"] > 0) | (onfield["assist"] > 0)].nflId
defense_tracking = test_play["defense_raw"].loc[:, pd.IndexSlice[tacklers.tolist(), :]]
ball_carrier_tracking = test_play["ball_carrier_raw"]
# create a defense transformer and a ball_carrier transformer
# concat + transformer
defense_tracking

Keys: ['offense_geometric', 'defense_geometric', 'offense_raw', 'defense_raw', 'ball_carrier_raw', 'play_features', 'game_id', 'play_id', 'player_tracking', 'event_timeseries', 'players_on_the_field', 'tackle_successful', 'yards_after_contact']

   47939.0
         x      y     s     a       o     dir
0    58.82  14.17  4.12  2.27  106.30  204.50
1    58.67  13.80  3.84  2.89   95.07  200.46
2    58.55  13.46  3.53  3.28   96.64  196.71
3    58.47  13.14  3.14  3.59   94.98  192.68
4    58.42  12.85  2.78  3.75   93.20  187.53
5    58.40  12.60  2.38  3.78   92.19  181.73
6    58.41  12.38  2.09  3.50   92.19  175.30
7    58.44  12.19  1.86  3.27   89.87  166.65
8    58.50  12.02  1.68  3.04   89.87  157.31
9    58.57  11.86  1.70  2.21   91.90  150.85
10   58.66  11.71  1.79  1.56   95.27  146.18
11   58.78  11.56  1.97  1.37   98.39  142.48
12   58.91  11.39  2.16  1.32  102.25  140.53
13   59.04  11.19  2.56  1.98  105.84  146.11
14   59.19  10.96  2.87  2.66  107.40  149.66
15   59.33  10.69  3.16  2.87  108.33  152.72
16   59.47  10.39  3.49  2.91  109.47  156.49
17   59.58  10.01  3.99  3.58  106.61  163.15
18   59.69   9.60  4.34  3.57  106.00  167.01
19   59.76   9.15  4.67  3.47  105.30  171.05
20   59.80   8.66  4.99  3.37  103.52  175.46
21   59.78   8.14  5.24  3.45  144.93  180.86

In [25]:
games = pd.read_csv("../data/nfl-big-data-bowl-2024/games.csv")
plays = pd.read_csv("../data/nfl-big-data-bowl-2024/plays.csv")

In [31]:
formations = plays["offenseFormation"].value_counts(dropna=False).reset_index()
display(formations)
FORMATIONS = dict(zip(formations["offenseFormation"], formations.index))

  offenseFormation  count
0          SHOTGUN   6378
1       SINGLEBACK   3524
2           I_FORM    929
3            EMPTY    850
4           PISTOL    599
5            JUMBO    115
6          WILDCAT     87
7              NaN      4

In [32]:
plays["defendersInTheBox"].value_counts(dropna=False).reset_index()

    defendersInTheBox  count
0                 6.0   5500
1                 7.0   3692
2                 8.0   1457
3                 5.0   1238
4                 4.0    319
5                 9.0    166
6                 3.0     51
7                10.0     35
8                11.0     19
9                 NaN      5
10                2.0      3
11                1.0      1

In [36]:
np.digitize(None, [1, 2, 3])

TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

In [41]:
import pandas as pd
import numpy as np

plays = pd.read_csv("../data/nfl-big-data-bowl-2024/plays.csv")
games = pd.read_csv("../data/nfl-big-data-bowl-2024/games.csv")
len(plays)

12486

In [7]:
plays_aug = pd.merge(plays, games, how="left", on="gameId")
plays_aug

,gameId,playId,ballCarrierId,ballCarrierDisplayName,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,...,foulNFLId1,foulNFLId2,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr,homeFinalScore,visitorFinalScore
0,2022100908,3537,48723,Parker Hesse,(7:52) (Shotgun) M.Mariota pass short middle t...,4,1,10,ATL,TB,...,NaN,NaN,2022,5,10/09/2022,13:00:00,TB,ATL,21,15
1,2022091103,3126,52457,Chase Claypool,(7:38) (Shotgun) C.Claypool right end to PIT 3...,4,1,10,PIT,CIN,...,NaN,NaN,2022,1,09/11/2022,13:00:00,CIN,PIT,20,23
2,2022091111,1148,42547,Darren Waller,(8:57) D.Carr pass short middle to D.Waller to...,2,2,5,LV,LAC,...,NaN,NaN,2022,1,09/11/2022,16:25:00,LAC,LV,24,19
3,2022100212,2007,46461,Mike Boone,(13:12) M.Boone left tackle to DEN 44 for 7 ya...,3,2,10,DEN,LV,...,NaN,NaN,2022,4,10/02/2022,16:25:00,LV,DEN,32,23
4,2022091900,1372,47857,Devin Singletary,(8:33) D.Singletary right guard to TEN 32 for ...,2,1,10,BUF,TEN,...,NaN,NaN,2022,2,09/19/2022,19:15:00,BUF,TEN,41,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12481,2022100204,123,43293,Ezekiel Elliott,(13:31) E.Elliott right tackle to WAS 38 for 1...,1,1,10,DAL,WAS,...,NaN,NaN,2022,4,10/02/2022,13:00:00,DAL,WAS,25,10
12482,2022091200,3467,46189,Will Dissly,(6:08) G.Smith pass short right to W.Dissly to...,4,1,10,SEA,DEN,...,NaN,NaN,2022,1,09/12/2022,20:15:00,SEA,DEN,17,16
12483,2022101605,3371,44860,Joe Mixon,(9:35) (Shotgun) J.Mixon left end to CIN 47 fo...,4,1,10,CIN,NO,...,NaN,NaN,2022,6,10/16/2022,13:00:00,NO,CIN,26,30
12484,2022100207,2777,52449,Jonathan Taylor,(2:02) (Shotgun) J.Taylor up the middle to TEN...,3,1,10,IND,TEN,...,NaN,NaN,2022,4,10/02/2022,13:00:00,IND,TEN,17,24
12485,2022102308,905,54572,Dameon Pierce,(12:51) C.Heck reported in as eligible. D.Pie...,2,3,1,HOU,LV,...,NaN,NaN,2022,7,10/23/2022,16:05:00,LV,HOU,38,20

In [45]:
quarter = pd.get_dummies(plays_aug["quarter"], prefix="Q", prefix_sep="").rename(columns={"Q5": "OT"}).astype(int)

down = pd.get_dummies(plays_aug["down"], prefix="down").astype(int)

YARDAGE_BINS =  [0, 3, 7, 10, 100]
YARDAGE_CATEGORIES = ["short", "medium", "long", "very_long"]
yardage = pd.get_dummies(pd.cut(plays_aug["yardsToGo"], bins=YARDAGE_BINS, right=True, include_lowest=True, labels=YARDAGE_CATEGORIES), prefix="yardage").astype(int)

time = plays_aug["gameClock"].str.split(":", expand=True)
time_remaining = pd.Series(time.loc[:, 0].astype(int) + time.loc[:, 1].astype(int) / 60., name="time")


home_team_has_the_ball = (plays_aug["possessionTeam"] == plays_aug["homeTeamAbbr"])
possession_team_score =  plays_aug["preSnapHomeScore"].where(home_team_has_the_ball, plays_aug["preSnapVisitorScore"])
defensive_team_score =  plays_aug["preSnapVisitorScore"].where(home_team_has_the_ball, plays_aug["preSnapHomeScore"])
possession_team_deficit = possession_team_score - defensive_team_score

formation = pd.get_dummies(plays_aug["offenseFormation"], prefix="formation").astype(int)

DEFENDERS_IN_BOX_BINS = [0, 4, 5, 6, 7, 8, 12]
defenders_in_box = pd.get_dummies(pd.cut(np.nan_to_num(plays_aug["defendersInTheBox"], nan=-1), bins=DEFENDERS_IN_BOX_BINS, right=True), prefix="n_def_in_box").astype(int)

pd.concat([quarter, down, yardage, time_remaining, possession_team_score, defensive_team_score, possession_team_deficit, formation, defenders_in_box], axis=1)

,Q1,Q2,Q3,Q4,OT,down_1,down_2,down_3,down_4,yardage_short,...,formation_PISTOL,formation_SHOTGUN,formation_SINGLEBACK,formation_WILDCAT,"n_def_in_box_(0, 4]","n_def_in_box_(4, 5]","n_def_in_box_(5, 6]","n_def_in_box_(6, 7]","n_def_in_box_(7, 8]","n_def_in_box_(8, 12]"
0,0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
2,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
4,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12481,1,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
12482,0,0,0,1,0,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
12483,0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
12484,0,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
12485,0,1,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0

In [40]:
play_features = test_play['play_features']
# one-hot encode quarter (1, 2, 3, 4 ,  5  - for OT),
quarter = np.zeros(5)
quarter[play_features["quarter"] - 1] = 1.

# #one-hot encode down (1, 2, 3, 4),
down = np.zeros(4)
down[play_features["down"] - 1] = 1.

# bucket yards to go (0, 3], (3, 7], (7, 10], (10, inf],
bins = [0, 3, 7, 10, 100]
yards_to_go = np.zeros(len(bins) - 1)
yards_to_go_bin = np.digitize(play_features["yardsToGo"], bins=bins)
yards_to_go[yards_to_go_bin - 1] = 1.

# clock -> minutes, 
minutes, seconds = play_features["gameClock"].split(":")
time_remaining = int(minutes) + int(seconds) / 60.

# keep scores and yard number, add deficit,
home_team_has_the_ball = play_features["possessionTeam"] == "BUF" # play_features["homeTeam"]
possession_team_score = play_features["preSnapHomeScore"] if home_team_has_the_ball else play_features["preSnapVisitorScore"]
defensive_team_score = play_features["preSnapVisitorScore"] if home_team_has_the_ball else play_features["preSnapHomeScore"]
possession_team_deficit = possession_team_score - defensive_team_score

# onehot encode offense formation (x5), keep def in box as one hot encoded (x12)
formation = np.zeros(len(formations))
formation[FORMATIONS[play_features["offenseFormation"]]] = 1.

defenders_in_box_bins =  [0, 4, 5, 6, 7, 8, 12]
defenders_in_box = np.zeros(len(defenders_in_box_bins) - 1)
defenders_in_box_index = np.digitize(np.nan_to_num(play_features["defendersInTheBox"], nan=-1), bins=defenders_in_box_bins)
defenders_in_box[defenders_in_box_index - 1] = 1.

final_features = np.concatenate([quarter, down, yards_to_go, [time_remaining, possession_team_score, defensive_team_score, possession_team_deficit], formation, defenders_in_box])
# predict play result (yards gained/lost)
final_features.shape

(31,)

In [48]:
import pickle
train_df = pickle.load(open("../data/nfl-big-data-bowl-2024/play_by_play_train.pkl", "rb"))

In [51]:
train_df[0]["play_features_encoded"]

Q1                       0.000000
Q2                       0.000000
Q3                       1.000000
Q4                       0.000000
OT                       0.000000
down_1                   1.000000
down_2                   0.000000
down_3                   0.000000
down_4                   0.000000
yardage_short            0.000000
yardage_medium           0.000000
yardage_long             0.000000
yardage_very_long        1.000000
time                     2.866667
preSnapHomeScore         0.000000
preSnapVisitorScore     24.000000
0                      -24.000000
formation_EMPTY          0.000000
formation_I_FORM         1.000000
formation_JUMBO          0.000000
formation_PISTOL         0.000000
formation_SHOTGUN        0.000000
formation_SINGLEBACK     0.000000
formation_WILDCAT        0.000000
n_def_in_box_(0, 4]      0.000000
n_def_in_box_(4, 5]      0.000000
n_def_in_box_(5, 6]      0.000000
n_def_in_box_(6, 7]      1.000000
n_def_in_box_(7, 8]      0.000000
n_def_in_box_(8, 12]     0.000000
Name: (2022103006, 2674), dtype: float64